-- 상품코드 별 매출액 (판매가 * 판매량) 합계 출력
-- 매출액 기준 내림차순, 상품코드 오름차순

SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT JOIN OFFLINE_SALE USING(PRODUCT_ID)
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC