WITH OFFLINES AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)

SELECT PRODUCT_CODE, (PRICE * AMOUNT) AS SALES
FROM PRODUCT JOIN OFFLINES USING(PRODUCT_ID)
ORDER BY SALES DESC, PRODUCT_CODE ASC