-- 입양을 간 동물
-- 보호 기간이 가장 길었던 동물 두 마리
-- 아이디, 이름 조회
-- 보호 기간이 긴 순
WITH ANSWER AS (
    SELECT I.ANIMAL_ID, I.NAME, TIMESTAMPDIFF(SECOND, I.DATETIME, O.DATETIME) AS TIME
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O USING (ANIMAL_ID)
    ORDER BY TIME DESC
    LIMIT 2
)

SELECT ANIMAL_ID, NAME
FROM ANSWER