-- 중고 거래 게시물을 3건 이상 등록한 사용자 ID, 닉네임,전체주소,전화번호 조회
-- 전체 주소는 시, 도로명, 상세주소 함께 출력
-- 전화번호 XXX-XXXX-XXXX 하이픈 삽입
-- 회원ID 내림차순

WITH BOARD_THREE AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)

SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
CONCAT(LEFT(TLNO, 3), '-', MID(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) AS 전화번호
FROM USED_GOODS_USER
WHERE USER_ID IN (SELECT * FROM BOARD_THREE)
ORDER BY USER_ID DESC


