-- 평균 대여 기간 7일 이상인 자동차
-- 자동차ID, 평균 대여 기간(소수 두번째 자리 반올림)
-- 평균 대여 기간 기준 내림차순, 자동차 ID기준 내림차순

SELECT CAR_ID, ROUND(AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

# SELECT TIMESTAMPDIFF(DAY, START_DATE, END_DATE)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY