-- 생산일자 2022년 5월, 총매출
-- 총매출 기준 내림차순, 식품 id 오름차순
WITH ORDERS AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
)


SELECT PRODUCT_ID, PRODUCT_NAME, (PRICE * AMOUNT)AS TOTAL
FROM FOOD_PRODUCT
JOIN ORDERS USING(PRODUCT_ID)
ORDER BY TOTAL DESC, PRODUCT_ID