-- 코드를 입력하세요
SELECT P.PRODUCT_CODE AS PRODUCT_CODE, SUM(P.PRICE*OS.SALES_AMOUNT) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE OS ON (P.PRODUCT_ID = OS.PRODUCT_ID)
GROUP BY P.PRODUCT_CODE
ORDER BY SUM(P.PRICE*OS.SALES_AMOUNT) DESC, PRODUCT_CODE;