-- 자동차 종류가 '트럭' 인 자동차의 대여 기록
-- 대여 기록 별 대여 금액 
-- 대여 기록 ID, 대여 금액 리스트 출력
-- 대여 금액 내림차순, 대여 기록 ID 내림차순

WITH DATES AS (
    SELECT *, TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1 AS DAY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY   
    
), CTE AS (
    SELECT DISCOUNT_RATE, DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)


SELECT H.HISTORY_ID, 
    ROUND((C.DAILY_FEE * H.DAY) * 0.01 * (100 - (
        CASE
            WHEN H.DAY >= 90 THEN (SELECT DISCOUNT_RATE FROM CTE WHERE DURATION_TYPE = '90일 이상')
            WHEN H.DAY >= 30 THEN (SELECT DISCOUNT_RATE FROM CTE WHERE DURATION_TYPE = '30일 이상')
            WHEN H.DAY >= 7 THEN (SELECT DISCOUNT_RATE FROM CTE WHERE DURATION_TYPE = '7일 이상')
            ELSE 0
            END
        )
    ),0
) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN DATES H USING(CAR_ID)
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
