-- FIRST HALF 상반기 주문 정보
-- JULY 각각 아이스크림 공장에서 가게까지 7월 주문량
-- 7월 아이스크림 총 주문량 + 상반기의 아이스크림 총 주문량

WITH JULY_ICE AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
), FINAL AS (
    SELECT FLAVOR, (TOTAL_ORDER + TOTAL) AS TOTAL
    FROM FIRST_HALF JOIN JULY_ICE USING(FLAVOR)
    ORDER BY TOTAL DESC
    LIMIT 3
)

SELECT FLAVOR
FROM FINAL 

