-- 리뷰를 가장 많이 작성한 회원
-- 그 회원의 리뷰들을 조회

WITH RANKING AS(
    SELECT MEMBER_ID, DENSE_RANK() OVER( ORDER BY COUNT(MEMBER_ID) DESC) AS REVIEW_RANK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW JOIN MEMBER_PROFILE USING(MEMBER_ID)
JOIN RANKING USING(MEMBER_ID)
WHERE REVIEW_RANK = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT 