-- 자동차 종류가 '세단'인 자동차들
-- 10월에 대여를 시작한 기록이 있는 자동차 ID리스트
-- 자동차 ID리스트는 중복이 없어야함
-- 자동차 ID기준으로 내림차순 정렬

WITH HISTORY AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) = 10
)

SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID IN (SELECT * FROM HISTORY)
AND CAR_TYPE = '세단'
ORDER BY CAR_ID DESC